/// Flutter icons VkIcons
/// Copyright (C) 2024 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  VkIcons
///      fonts:
///       - asset: fonts/VkIcons.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class VkIcons {
  VkIcons._();

  static const _kFontFam = 'VkIcons';
  static const String? _kFontPkg = null;

  static const IconData vk_logo = IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData three_dots_vertical = IconData(0xe801, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData vk_logo_outline = IconData(0xe802, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
